import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by next-pwa on every build. Linting minified bundles produced
    // ~100 findings that drowned out the handful in real source, and made
    // `npm run lint` fail depending on which artifacts happened to be present.
    "public/sw.js",
    "public/workbox-*.js",
    "public/worker-*.js",
    "public/*.js.map",
  ]),
  {
    // One-off Node maintenance scripts, run directly with `node` rather than
    // bundled. They are CommonJS, so `require` is correct there.
    files: ["scripts/**/*.js"],
    rules: {
      "@typescript-eslint/no-require-imports": "off",
    },
  },
]);

export default eslintConfig;
